### ISSUE TITLE
Predicting only positive regulations

### ISSUE THREAD

**Issue by hongyaz** [emiraldi/infTRN_lassoStARS#3]
Hi,

Thank you for the cool software! 

I was wondering that if it is possible to add restrictions to the algorithm to make it predict only positive regulations. The reason is that there are TFs that are known to positively regulate targets. I was thinking if adding this kind of restrictions can produce interesting results for this set of TFs (using only positive regulations to explain the gene expression data). Could you share your thoughts on whether it is possible and how to make this kind of changes? Thank you very much ahead of time!

**Comment by emiraldi** [comment]
Hello! Thanks for the question! There are a couple of ways to incorporate information about whether a TF positively or negatively regulates a gene. 
(1) For example, the priors of TF-gene interactions are signed. If a TF is known to activate (repress) a gene, then the interaction will be positive (negative). Then, if you use the signed prior to estimate TF activity, the signs help you get the TF activity pattern right, and correctly signed interactions are more likely to be recovered from gene expression modeling. Some priors are signed (e.g., interactions derived from the TRRUST database or TF KO experiments are signed), while others information sources don't automatically provide signs (ATAC-seq, ChIP-seq) -- but this info could be added based on prior knowledge / literature. 
(2) Knowledge of TF interaction sign could be included as an additional constraint in model optimization with adaptive LASSO (not currently an option with this codebase). I like this option less than (1) because many TFs are not strictly activators or repressors, instead their ability to promote expression is dependent on the TFs that are co-bound and the co-regulators (acetylases, etc.) that collectively they can recruit. 
--> So, while I like the idea of accounting for sign in the prior to improve TF activity estimation and ultimately the sign of interactions learned from gene expression modeling (1), I don't like "forcing" the gene expression model to be consistent with prior knowledge (2) -- although in a very well-studied system "forcing" might be justified and could improve sign prediction of other TFs in the model (as the signs of the TFs are dependent on each other in a multivariate regression framework).
-- Emily

**Comment by hongyaz** [comment]
@emiraldi Thank you Emily for the detailed explanations! Your reply really helps me in better understanding and applying your software. Sorry that I didn't see this and reply earlier, but I will definitely think more about the two options that you described!
